udp:
  services:
    minecraft:
      loadBalancer:
        servers:
          - address: "minecraft:25565"
tcp:
  services:
    minecraft:
      loadBalancer:
        servers:
          - address: "minecraft:25565"